# Generated by Django 3.0.8 on 2020-07-14 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='code',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='state',
        ),
    ]
