# Generated by Django 3.0.8 on 2020-07-16 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200714_2344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipping',
            new_name='ShippingInformation',
        ),
    ]
